# action.yml
name: 'Formal Mathematics Library Visualizer'
description: 'Add a visual representation of a formal mathematics library to your pages'
inputs:
  language:
    description: 'Language of your formal library. Supported options are Agda or Lean.'
    options:
      - agda
      - lean
      - autodetect
    initial: autodetect
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.language }}
