# action.yml
name: 'Formal Mathematics Library Visualizer'
description: 'Add a visual representation of a formal mathematics library to your README.'
inputs:
  language:
    description: 'Language of your formal library. Supported options are Agda or Lean.'
    options:
      - agda
      - lean
      - autodetect
    initial: autodetect
runs:
  - uses: satackey/action-docker-layer-caching@v0.0.11
    continue-on-error: true
  args:
    - ${{ inputs.language }}
  